name: post to discord

on: push

jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: curl -d "content=messagecontenttest" ${{secrets.DISCORD_WEBHOOK_URL}}
      - run: curl -d '{"embeds":[{"type":"rich", "title":"test"}]}' ${{secrets.DISCORD_WEBHOOK_URL}}
